name: publish
on:
  push:
    branches:
      - '*'
jobs:
  publish-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo $PWD && ls -al ..
      - uses: primer/publish@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          args: '--dry-run --dir=$PWD'
